
const ref={customer:['全部客户','华联超市','城西便利','民生烟酒','万科物业'],supplier:['全部供应商','农夫山泉杭州经销','康师傅食品','顺丰物流'],warehouse:['全部仓库','总仓','东区仓','冷藏仓','退货仓'],user:['全部人员','张三','李四','王五','赵六'],status:['全部状态','草稿','待审核','已审核','已完成','已关闭'],goods:['全部商品','农夫山泉500ml*24','康师傅红烧牛肉面','临期酸奶200g']};
const masters={product:{group:'基础资料',name:'商品档案',tree:['全部商品','饮料','瓶装水','茶饮料','方便食品','日化护理'],cols:['商品编号','商品名称','规格型号','分类','品牌','基本单位','可售','可采购','标准售价','参考进价','库存下限','状态'],row:['SP001','农夫山泉500ml*24','500ml*24','瓶装水','农夫山泉','瓶','是','是','35.00','31.20','100','正常'],form:[['基础档案',['商品编号','商品名称','规格型号','商品分类','品牌','商品类型','保质期天数','存储属性','是否可售','是否可采购','是否可退','是否称重','是否预售','默认供应商','默认仓库','税率%','起订量','起订倍数','库存上限','库存下限','临期预警天数','状态']],['单位设置',null],['价格设置',null],['商品介绍',['商品介绍']]]},customer:{group:'基础资料',name:'门店/客户资料',tree:['全部客户','KA客户','流通客户','西湖区','朝阳线','拱墅区'],cols:['客户编码','客户名称','客户等级','联系人','手机','片区','线路','账期类型','信用额度','应收余额','状态'],row:['C001','华联超市','金牌','王店长','138****8888','西湖区','朝阳线','月结固定付款日','50000','12000','正常'],form:[['基本信息',['客户编码','客户名称','客户类型','客户等级','渠道类型','联系人','手机号','片区','线路','业务员','状态']],['地址信息',null],['账期设置',null],['开票信息',['发票抬头','税号','开户行','银行账号','开票地址','开票电话']],['导入修改',['导入匹配字段','可批量修改字段','失败处理']] ]},supplier:{group:'基础资料',name:'供应商资料',tree:['全部供应商','食品饮料供应商','物流服务商','设备耗材'],cols:['供应商编码','供应商名称','类型','联系人','到货天数','结算方式','账期类型','默认收款账户','应付余额','状态'],row:['G001','农夫山泉杭州经销','饮料供应商','赵经理','5','月结','月结固定付款日','工商银行 6222****','6600','正常'],form:[['基础信息',['供应商编码','供应商名称','供应商类型','联系人','联系电话','地址','到货天数','默认采购员','状态']],['结算设置',null],['收款账户',null],['发票信息',['发票抬头','税号','开票地址','开票电话']],['联系人',null]]}};
const simpleMasterNames={goodsCategory:'商品分类',brand:'品牌管理',unit:'单位管理',warehouse:'仓库资料',priceGroup:'价格组设置',customerPrice:'客户价格设置',territory:'片区管理',routeLine:'线路管理',employee:'人员信息',department:'部门管理',owner:'货主信息',expenseType:'费用类型',counterparty:'往来单位',fundAccount:'资金账户',userManage:'用户管理',roleManage:'权限组管理',systemParam:'系统参数',billNoRule:'单据编号规则',precisionSetting:'显示精度设置',operationLog:'操作日志',importExportCenter:'导入/导出中心',salesReport:'销售报表',purchaseReport:'采购报表',stockReport:'库存报表',financeReport:'财务报表'};
Object.entries(simpleMasterNames).forEach(([id,name])=>masters[id]={group:['userManage','roleManage','systemParam','billNoRule','precisionSetting','operationLog','importExportCenter'].includes(id)?'系统管理':id.includes('Report')?'报表中心':'基础资料',name,tree:['全部','启用','停用'],cols:[name+'编码',name+'名称','类型/分组','状态','备注'],row:[id.toUpperCase()+'001',name+'示例','默认','正常','示例数据'],form:[[name+'信息',[name+'编码',name+'名称','类型/分组','状态','备注']]]});
const bill={purchaseOrder:['采购订单','采购单号','供应商','采购员','仓库','状态'],purchaseInbound:['采购入库','入库单号','采购单号','供应商','仓库','状态'],purchaseReceipt:['采购收货单','收货单号','入库单号','供应商','应付生成','开票状态'],purchaseReturn:['采购退货单','退货单号','供应商','仓库','退货原因','状态'],purchaseExpense:['采购费用单','费用单号','费用类型','供应商/往来单位','分摊状态','应付生成'],purchaseInvoice:['采购发票','发票单号','发票号码','供应商','勾稽状态','认证状态'],salesOrder:['销售订单','销售单号','客户','业务员','仓库','状态'],salesOutbound:['销售出库','出库单号','销售单号','客户','仓库','状态'],salesReceipt:['销售收货单','收货单号','销售单号','客户','签收状态','应收生成'],salesReturn:['销售退货单','退货单号','客户','退货原因','仓库','状态'],stockBalance:['库存余额','商品','仓库','库存状态','批次','成本分组'],stockLedger:['库存流水','流水号','商品','仓库','批次','来源单据','方向'],stockLock:['库存锁定','锁定单号','来源单据','商品','仓库','锁定状态'],batchStock:['批次库存','商品','仓库','批次','效期状态','库存状态'],stockWarning:['库存预警','商品','仓库','预警类型','处理状态'],stockTake:['库存盘点','盘点单号','仓库','盘点类型','状态'],otherIn:['其他入库','入库单号','仓库','入库原因','状态'],otherOut:['其他出库','出库单号','仓库','出库原因','状态'],transfer:['调拨单','调拨单号','调出仓库','调入仓库','状态'],damage:['报损单','报损单号','仓库','报损类型','状态'],costAdjust:['成本调整单','调整单号','仓库','调整方式','状态'],stockAdjust:['库存调整单','调整单号','仓库','调整原因','状态'],ar:['应收账款/结算','应收单号','客户/往来单位','核销状态','逾期状态'],ap:['应付账款/结算','应付单号','供应商/往来单位','核销状态','到期状态'],financeExpense:['费用单','费用单号','费用方向','费用类型','对象类型','对象名称','状态'],receiptPayment:['收款单/付款单','单据编号','对象类型','对象名称','收付款方式','资金账户','核销状态'],salesInvoice:['销售发票','发票单号','客户','发票类型','开票状态','勾稽状态']};
const nav={首页:[['dashboard','经营概览']],基础资料:[['product','商品档案'],['goodsCategory','商品分类'],['brand','品牌管理'],['unit','单位管理'],['customer','门店/客户资料'],['supplier','供应商资料'],['warehouse','仓库资料'],['priceGroup','价格组设置'],['customerPrice','客户价格设置'],['territory','片区管理'],['routeLine','线路管理'],['employee','人员信息'],['department','部门管理'],['owner','货主信息'],['expenseType','费用类型'],['counterparty','往来单位'],['fundAccount','资金账户']],销售管理:[['quick','销售快速开单'],['salesOrder','销售订单'],['salesOutbound','销售出库'],['salesReceipt','销售收货单'],['salesReturn','销售退货单'],['salesInvoice','销售发票']],采购管理:[['purchaseOrder','采购订单'],['purchaseInbound','采购入库'],['purchaseReceipt','采购收货单'],['purchaseReturn','采购退货单'],['purchaseExpense','采购费用单'],['purchaseInvoice','采购发票']],库存管理:[['stockBalance','库存余额'],['stockLedger','库存流水'],['stockLock','库存锁定'],['batchStock','批次库存'],['stockWarning','库存预警'],['stockTake','库存盘点'],['otherIn','其他入库'],['otherOut','其他出库'],['transfer','调拨单'],['damage','报损单'],['costAdjust','成本调整单'],['stockAdjust','库存调整单']],财务管理:[['ar','应收账款/结算'],['ap','应付账款/结算'],['financeExpense','费用单'],['receiptPayment','收款单/付款单']],系统管理:[['init','数据初始化向导'],['userManage','用户管理'],['roleManage','权限组管理'],['systemParam','系统参数'],['billNoRule','单据编号规则'],['precisionSetting','显示精度设置'],['operationLog','操作日志'],['importExportCenter','导入/导出中心']],报表中心:[['salesReport','销售报表'],['purchaseReport','采购报表'],['stockReport','库存报表'],['financeReport','财务报表']]};
let activeTop='首页',current='dashboard';function init(){renderMenu();route('dashboard')}function renderMenu(){let html='';Object.keys(nav).forEach(top=>{let open=top===activeTop;html+=`<div class="lvl1-item ${open?'on':''}" onclick="activeTop='${top}';current=nav['${top}'][0][0];renderMenu();route(current)"><span class="dot"></span>${top}</div>`;if(open)html+=`<div class="submenu">${nav[top].map(i=>`<div class="lvl2-item ${i[0]===current?'on':''}" onclick="event.stopPropagation();route('${i[0]}')">${i[1]}</div>`).join('')}</div>`});side.innerHTML=html}function route(id){current=id;Object.keys(nav).forEach(t=>{if(nav[t].some(i=>i[0]===id))activeTop=t});renderMenu();if(id==='dashboard')return dashboard();if(id==='quick')return quick();if(id==='init')return initPage();if(masters[id])return master(id);if(bill[id])return billList(id)}
function dashboard(){title.textContent='经营概览';desc.textContent='企业经销数据、排行与待办';content.innerHTML=`<div class="cards">${[['动销门店数','286'],['订单金额','¥82,450'],['出库金额','¥76,320'],['退货金额','¥3,180'],['净销售额','¥79,270'],['毛利额','¥18,920'],['今日收款额/总应收','¥56,200/¥1.28M'],['今日付款额/总应付','¥32,800/¥860K']].map(x=>`<div class="card"><div class="label">${x[0]}</div><div class="value">${x[1]}</div></div>`).join('')}</div><div class="rank-grid"><div class="rank-card"><h3>商品动销排行</h3>${rank(['农夫山泉','康师傅面','统一冰红茶'])}</div><div class="rank-card"><h3>商品大类动销排行</h3>${rank(['饮料','方便食品','休闲零食'])}</div><div class="rank-card"><h3>门店销售排行</h3>${rank(['华联超市','城西便利','民生烟酒'])}</div><div class="rank-card"><h3>业务员销售排行</h3>${rank(['张三','李娜','王五'])}</div></div>`}function rank(a){return `<table><tr><th>排名</th><th>名称</th><th>数值</th></tr>${a.map((x,i)=>`<tr><td>${i+1}</td><td>${x}</td><td class="num">¥${(12000-i*2100).toLocaleString()}</td></tr>`).join('')}</table>`}
function selectFor(f){if(f.includes('客户'))return `<select>${ref.customer.map(x=>`<option>${x}</option>`).join('')}</select>`;if(f.includes('供应商'))return `<select>${ref.supplier.map(x=>`<option>${x}</option>`).join('')}</select>`;if(f.includes('仓库'))return `<select>${ref.warehouse.map(x=>`<option>${x}</option>`).join('')}</select>`;if(f.includes('商品'))return `<select>${ref.goods.map(x=>`<option>${x}</option>`).join('')}</select>`;if(f.includes('状态'))return `<select>${ref.status.map(x=>`<option>${x}</option>`).join('')}</select>`;if(f.includes('日期'))return `<input value="2026-06-01 ~ 2026-06-13">`;return `<input placeholder="${f}">`}function filter(fields){return `<div class="filter">${fields.map(f=>`<div class="fi"><label>${f}</label>${selectFor(f)}</div>`).join('')}<button class="btn primary">查询</button><button class="btn">重置</button><button class="btn">展开更多</button></div>`}function table(cols,row){return `<div class="tablebox"><div class="toolbar"><b>记录列表</b><div class="spacer"></div><button class="btn" onclick="openFieldSetting()">字段设置</button><button class="btn" onclick="toast('已创建主单导出任务')">导出主单</button><button class="btn" onclick="toast('已创建明细导出任务')">导出明细</button></div><div class="scroll"><table><tr>${cols.map(c=>`<th onclick="toast('按 ${c} 排序')">${c} ↕</th>`).join('')}<th class="fixed-action">操作</th></tr><tr>${row.map((x,i)=>`<td class="${/金额|余额|数量|单价|成本|额度/.test(cols[i])?'num':''}">${fmt(x)}</td>`).join('')}<td class="fixed-action"><span class="link" onclick="edit()">编辑</span><span class="link" onclick="toast('已审核')">审核</span></td></tr></table></div><div class="sum"><span>当前页合计：金额 <b>¥1,000.00</b></span><span>数量 <b>100</b></span><span>查询总合计：金额 <b>¥18,000.00</b></span></div></div>`}function fmt(x){return ['正常','已审核'].includes(x)?`<span class="badge ok">${x}</span>`:['待审核','未核销'].includes(x)?`<span class="badge wait">${x}</span>`:x}
function master(id){let m=masters[id];title.textContent=m.name;desc.textContent='基础资料列表与页面式编辑';content.innerHTML=`<div class="layout2"><div class="tree">${m.tree.map((x,i)=>`<div class="${i===0?'sel':''}">${x}</div>`).join('')}</div><div>${filter(['关键字','状态'])}<div style="text-align:right;margin-bottom:10px"><button class="btn primary" onclick="edit('new')">新建</button><button class="btn">批量编辑</button><button class="btn">导入修改</button><button class="btn">导出</button></div>${table(m.cols,m.row)}</div></div>`}function edit(mode='edit'){if(masters[current])return masterEdit(mode);if(bill[current])return billEdit(mode)}function masterEdit(mode){let m=masters[current];title.textContent=(mode==='new'?'新建':'编辑')+' - '+m.name;content.innerHTML=`<div class="form-card"><div class="form-head"><b>${title.textContent}</b><div class="spacer"></div><button class="btn" onclick="master('${current}')">返回列表</button><button class="btn primary" onclick="toast('已保存')">保存</button></div><div class="form-body"><div class="tabs"><span class="on">基础信息</span><span>扩展信息</span><span>明细信息</span></div><div class="section"><h3>基础信息</h3><div class="grid4">${m.cols.slice(0,14).map(f=>`<div class="field"><label>${f}</label>${selectFor(f)}</div>`).join('')}</div></div>${current==='customer'||current==='supplier'?period():''}${current==='supplier'?accounts():''}${current==='product'?productExtra():''}</div></div>`}function productExtra(){return `<div class="section"><h3>单位与价格</h3>${matrix(['项目','基本单位','大单位','中单位'],[['单位','瓶','箱',''],['换算率','1','24',''],['标准售价','2.40','',''],['参考进价','1.00','','']])}</div>`}function period(){return `<div class="section"><h3>灵活账期</h3><div class="period-box"><div class="grid4">${['是否设账期','结算方式','账期类型','截账日','付款月/日','账期天数','控制方式','额度'].map(f=>`<div class="field"><label>${f}</label>${selectFor(f)}</div>`).join('')}</div></div></div>`}function accounts(){return `<div class="section"><h3>供应商收款账户</h3>${matrix(['账户名称','开户行','银行账号','收款户名','默认','状态'],[['默认账户','工商银行','6222****','供应商公司','是','正常']])}</div>`}
function billList(id){let b=bill[id];title.textContent=b[0];desc.textContent='单据列表、新建、编辑、审核';content.innerHTML=`<div class="bill-tabs"><span class="on">全部</span><span>待审核 3</span><span>已审核</span></div>${filter(b.slice(1))}<div style="text-align:right;margin-bottom:10px"><button class="btn primary" onclick="edit('new')">新建</button><button class="btn">导入</button><button class="btn">导出</button><button class="btn">打印</button></div>${table([b[1],...b.slice(2),'金额','状态'],[id.toUpperCase()+'001',...b.slice(2).map(x=>x.includes('客户')?'华联超市':x.includes('供应商')?'农夫山泉杭州经销':x.includes('仓库')?'总仓':'示例'),'1000.00','待审核'])}`}function billEdit(mode){let b=bill[current];title.textContent=(mode==='new'?'新建':'编辑')+' - '+b[0];content.innerHTML=`<div class="form-card"><div class="form-head"><b>${title.textContent}</b><div class="spacer"></div><button class="btn" onclick="billList('${current}')">返回列表</button><button class="btn primary" onclick="toast('已提交/审核')">提交/审核</button></div><div class="form-body"><div class="section"><h3>单据头</h3><div class="grid4">${b.slice(1).map(f=>`<div class="field"><label>${f}</label>${selectFor(f)}</div>`).join('')}</div></div><div class="section"><h3>明细信息</h3>${matrix(['商品/项目','仓库','业务单位','开单数量','换算率','基本单位','基本单位数量','单价','金额','成本单价','成本金额','批次','操作'],[['示例商品','总仓','箱','10','24','瓶','240','35.00','350.00','31.20','312.00','B202606','删除']])}<button class="btn">新增明细行</button></div></div><div class="summary"><span>数量 <b>100</b></span><span>金额 <b>¥1,000.00</b></span><span>成本 <b>¥800.00</b></span></div></div>`}
function quick(){title.textContent='销售快速开单';desc.textContent='直接录入、快捷键、库存校验';content.innerHTML=`<div class="form-card"><div class="form-head"><b>销售快速开单</b><div class="spacer"></div><button class="btn primary" onclick="toast('订单已审核并锁库存')">审核并打印</button></div><div class="form-body"><div class="grid4"><div class="field"><label>客户</label>${selectFor('客户')}</div><div class="field"><label>仓库</label>${selectFor('仓库')}</div><div class="field"><label>业务员</label>${selectFor('业务员')}</div><div class="field"><label>结算方式</label><select><option>月结30天</option><option>现结</option></select></div></div><div class="risk">欠款 ¥12,000　逾期 ¥2,000　信用额度 ¥50,000　可用额度 ¥38,000</div>${matrix(['商品','仓库','业务单位','开单数量','换算率','基本单位','基本单位数量','可用库存','单价','金额','成本','毛利'],[['农夫山泉500ml*24','总仓','箱','10','24','瓶','240','1200瓶','35.00','350.00','312.00','38.00']])}</div><div class="summary"><span>应收 <b>¥350.00</b></span><span>未收 <b>¥350.00</b></span></div></div>`}function initPage(){title.textContent='数据初始化向导';content.innerHTML=`<div class="form-card"><div class="form-head"><b>数据初始化向导</b></div><div class="form-body"><div class="tabs"><span class="on">初始化说明</span><span>基础资料</span><span>期初库存</span><span>期初应收</span><span>期初应付</span><span>资金账户</span><span>校验确认</span></div><div class="cards"><div class="card"><div class="label">商品资料</div><div class="value">4645</div></div><div class="card"><div class="label">期初库存</div><div class="value">12350</div></div><div class="card"><div class="label">期初应收</div><div class="value">¥126K</div></div><div class="card"><div class="label">资金余额</div><div class="value">¥58K</div></div></div><br><button class="btn">下载模板</button> <button class="btn primary" onclick="toast('上传并校验通过')">上传文件</button> <button class="btn primary" onclick="toast('系统已启用')">确认启用系统</button></div></div>`}function matrix(h,rows){return `<table class="matrix"><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr>${rows.map(r=>`<tr>${r.map(x=>`<td contenteditable>${x}</td>`).join('')}</tr>`).join('')}</table>`}function openFieldSetting(){document.body.insertAdjacentHTML('beforeend',`<div class="modal show" onclick="this.remove()"><div class="modalbox" onclick="event.stopPropagation()"><div class="modalhead">字段设置</div><div class="modalbody">${['单据号','客户/供应商','仓库','状态','金额','成本金额','备注'].map(x=>`<label style="display:block;margin:8px"><input type="checkbox" checked> ${x}</label>`).join('')}</div><div class="modalfoot"><button class="btn primary" onclick="this.closest('.modal').remove();toast('字段设置已保存')">保存</button></div></div></div>`)}function newRecord(){if(masters[current]||bill[current])edit('new');else toast('当前页面无需新建')}function backList(){if(masters[current])master(current);else if(bill[current])billList(current);else route(current)}function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
// ===== FINAL_PATCH_TREE_SCOPE_AND_MODULES =====
Object.assign(masters,{
  goodsCategory:{name:'商品分类',tree:['全部分类','食品饮料','饮料','瓶装水','茶饮料','方便食品','日化百货'],cols:['分类编码','分类名称','上级分类','层级','默认税率','商品数','状态'],row:['010101','瓶装水','饮料','3','13%','32','正常']},
  brand:{name:'品牌管理',tree:['全部品牌'],cols:['品牌编码','品牌名称','简拼','关联商品数','状态'],row:['B001','农夫山泉','NFSQ','86','正常']},
  unit:{name:'单位管理',tree:['全部单位'],cols:['单位编码','单位名称','可做基本单位','可做大单位','可做中单位','引用商品数','状态'],row:['U001','箱','是','是','否','128','正常']},
  warehouse:{name:'仓库资料',tree:['全部仓库'],cols:['仓库编码','仓库名称','仓库类型','库存类型','成本分组','负责人','状态'],row:['W001','总仓','正常仓','平台主仓','CG01','王五','正常']},
  priceGroup:{name:'价格组设置',tree:['全部价格组'],cols:['价格组编码','价格组名称','是否启用','排序','备注'],row:['PRICE1','批发价','是','1','默认销售价']},
  customerPrice:{name:'客户价格设置',tree:['全部客户价'],cols:['客户','商品','单位','专属价格','生效日期','失效日期','状态'],row:['华联超市','农夫山泉500ml*24','箱','34.50','2026-06-01','2026-12-31','正常']},
  territory:{name:'片区管理',tree:['全部片区','浙江','杭州','西湖区','拱墅区'],cols:['片区编码','片区名称','上级片区','层级','客户数','状态'],row:['T001','西湖区','杭州','3','230','正常']},
  routeLine:{name:'线路管理',tree:['全部线路'],cols:['线路编码','线路名称','默认司机','覆盖客户数','状态'],row:['R001','朝阳线','王司机','86','正常']},
  employee:{name:'人员信息',tree:['全部人员'],cols:['人员编码','姓名','部门','手机号','业务员','采购员','仓管员','状态'],row:['E001','张三','销售部','138****8888','是','否','否','在职']},
  department:{name:'部门管理',tree:['公司','销售部','采购部','仓储部','财务部'],cols:['部门编码','部门名称','上级部门','负责人','人员数','状态'],row:['D001','销售部','公司','张三','12','正常']},
  owner:{name:'货主信息',tree:['全部货主'],cols:['货主编码','货主名称','联系人','电话','默认货主','状态'],row:['H001','平台','管理员','138****0000','是','正常']},
  expenseType:{name:'费用类型',tree:['全部费用','采购费用','运费','装卸费','经营费用','房租','收入类费用'],cols:['费用编码','费用名称','上级费用','方向','采购费用','参与成本','状态'],row:['FY001','运费','采购费用','支出','是','是','正常']},
  counterparty:{name:'往来单位',tree:['全部往来单位'],cols:['往来单位编码','名称','类型','联系人','电话','结算方式','应收余额','应付余额','状态'],row:['WL001','顺丰物流','物流公司','陈经理','95338','月结','0','3200','正常']},
  fundAccount:{name:'资金账户',tree:['全部账户','现金','银行账户','线上账户'],cols:['账户编码','账户名称','类型','开户行','账号','当前余额','状态'],row:['A001','工行基本户','银行','工商银行','6222****','50300','正常']},
  userManage:{name:'用户管理',tree:['全部用户'],cols:['账号','姓名','手机号','权限组','数据范围','状态'],row:['admin','系统管理员','138****0000','管理员组','全部','正常']},
  roleManage:{name:'权限组管理',tree:['全部权限组'],cols:['权限组编码','权限组名称','用户数','菜单权限','字段权限','状态'],row:['ADMIN','管理员组','1','全部','全部','正常']},
  systemParam:{name:'系统参数',tree:['全部参数'],cols:['参数键','参数名称','当前值','默认值','分组','说明'],row:['CREDIT_CHECK_MODE','信用控制','提醒','提醒','销售','可改阻断']},
  billNoRule:{name:'单据编号规则',tree:['全部单据'],cols:['单据类型','前缀','日期格式','流水位数','重置周期','示例','状态'],row:['销售订单','SO','YYYYMMDD','4','按日','SO202606130001','正常']},
  precisionSetting:{name:'显示精度设置',tree:['全部精度'],cols:['参数','当前位数','最小允许','最大允许','说明'],row:['数量显示位数','2','2','6','只可增大']},
  operationLog:{name:'操作日志',tree:['全部日志'],cols:['操作时间','用户','模块','动作','单据号','结果'],row:['2026-06-13 10:00','admin','销售订单','审核','SO202606130001','成功']},
  importExportCenter:{name:'导入/导出中心',tree:['全部任务'],cols:['任务号','模块','类型','文件名','总数','成功','失败','状态'],row:['EXP001','销售订单','导出','销售订单.xlsx','100','100','0','已完成']},
  salesReport:{name:'销售报表',tree:['销售报表'],cols:['日期','客户','商品','数量','销售金额','成本金额','毛利'],row:['2026-06-13','华联超市','农夫山泉','10','350','312','38']},
  purchaseReport:{name:'采购报表',tree:['采购报表'],cols:['日期','供应商','商品','数量','采购金额','费用分摊'],row:['2026-06-13','农夫山泉杭州经销','农夫山泉','100','3500','333.33']},
  stockReport:{name:'库存报表',tree:['库存报表'],cols:['商品','仓库','实物库存','可用库存','成本单价','库存金额'],row:['农夫山泉','总仓','1200','1020','12.00','14400']},
  financeReport:{name:'财务报表',tree:['财务报表'],cols:['对象','应收余额','应付余额','逾期金额','资金余额'],row:['华联超市','350','0','0','-']}
});
Object.assign(bill,{purchaseReturn:['采购退货单','退货单号','供应商','仓库','退货原因','状态'],salesReturn:['销售退货单','退货单号','客户','退货原因','仓库','状态'],stockLedger:['库存流水','流水号','商品','仓库','批次','来源单据','方向'],stockLock:['库存锁定','锁定单号','来源单据','商品','仓库','锁定状态'],batchStock:['批次库存','商品','仓库','批次','效期状态','库存状态'],stockWarning:['库存预警','商品','仓库','预警类型','处理状态'],stockTake:['库存盘点','盘点单号','仓库','盘点类型','状态'],salesInvoice:['销售发票','发票单号','客户','发票类型','开票状态','勾稽状态']});
nav['基础资料']=[['product','商品档案'],['goodsCategory','商品分类'],['brand','品牌管理'],['unit','单位管理'],['customer','门店/客户资料'],['supplier','供应商资料'],['warehouse','仓库资料'],['priceGroup','价格组设置'],['customerPrice','客户价格设置'],['territory','片区管理'],['routeLine','线路管理'],['employee','人员信息'],['department','部门管理'],['owner','货主信息'],['expenseType','费用类型'],['counterparty','往来单位'],['fundAccount','资金账户']];
nav['销售管理']=[['quick','销售快速开单'],['salesOrder','销售订单'],['salesOutbound','销售出库'],['salesReceipt','销售收货单'],['salesReturn','销售退货单'],['salesInvoice','销售发票']];
nav['采购管理']=[['purchaseOrder','采购订单'],['purchaseInbound','采购入库'],['purchaseReceipt','采购收货单'],['purchaseReturn','采购退货单'],['purchaseExpense','采购费用单'],['purchaseInvoice','采购发票']];
nav['库存管理']=[['stockBalance','库存余额'],['stockLedger','库存流水'],['stockLock','库存锁定'],['batchStock','批次库存'],['stockWarning','库存预警'],['stockTake','库存盘点'],['otherIn','其他入库'],['otherOut','其他出库'],['transfer','调拨单'],['damage','报损单'],['costAdjust','成本调整单'],['stockAdjust','库存调整单']];
nav['系统管理']=[['init','数据初始化向导'],['userManage','用户管理'],['roleManage','权限组管理'],['systemParam','系统参数'],['billNoRule','单据编号规则'],['precisionSetting','显示精度设置'],['operationLog','操作日志'],['importExportCenter','导入/导出中心']];
nav['报表中心']=[['salesReport','销售报表'],['purchaseReport','采购报表'],['stockReport','库存报表'],['financeReport','财务报表']];
const treeMasterIds=['goodsCategory','fundAccount','expenseType','territory','department'];
master=function(id){let m=masters[id];title.textContent=m.name;desc.textContent=treeMasterIds.includes(id)?'树状资料：点击树节点查看该节点及下级记录':'普通基础资料：列表管理、查询、新建、编辑、导入导出';let ops=`<div style="text-align:right;margin-bottom:10px"><button class="btn primary" onclick="edit('new')">新建</button><button class="btn">批量编辑</button><button class="btn">导入修改</button><button class="btn">导出</button></div>`;if(treeMasterIds.includes(id)){content.innerHTML=`<div class="layout2"><div class="tree">${m.tree.map((x,i)=>`<div class="${i===0?'sel':''}" onclick="this.parentNode.querySelectorAll('div').forEach(d=>d.classList.remove('sel'));this.classList.add('sel');toast('已切换：${x}')">${x}</div>`).join('')}</div><div>${filter(['关键字','状态'])}${ops}${table(m.cols,m.row)}</div></div>`}else{content.innerHTML=`${filter(['关键字','状态'])}${ops}${table(m.cols,m.row)}<div class="risk">${m.name}采用普通列表管理，不使用左侧树状结构。</div>`}};
renderMenu();
// ===== END_FINAL_TREE_SCOPE_FIX =====
init();

