from pathlib import Path
import re
p=Path(r'E:\我的工作项目\erp-wms-tms\prototype\v1-erp-complete\index.html')
s=p.read_text(encoding='utf-8')
# append compact edit styles
s=s.replace('</style>', '.bill-edit-card{height:calc(100vh - 104px);display:flex;flex-direction:column}.bill-head-compact{padding:10px 14px;border-bottom:1px solid #e5edf7;background:#fff}.compact-grid{display:grid;grid-template-columns:repeat(6,1fr);gap:8px 14px}.compact-grid .field label{font-size:12px;color:#5d7896;margin-bottom:3px}.compact-grid .field input,.compact-grid .field select{height:30px}.detail-actions{display:flex;gap:8px;padding:10px 14px;align-items:center}.detail-fill{flex:1;min-height:0;overflow:auto;padding:0 14px 12px}.detail-fill table{min-width:1600px}.detail-fill th,.detail-fill td{height:34px}.bill-edit-summary{border-radius:0;margin:0}.mini-note{color:#5d7896}</style>')
new_func = '''function billEdit(mode){let b=bill[current];title.textContent=(mode==='new'?'新建':'编辑')+' - '+b[0];let headFields=b.slice(1);let detailHeads=['商品/项目','单位','数量','单价','金额','成本单价','成本金额','批次','备注','操作'];content.innerHTML=`<div class="form-card bill-edit-card"><div class="form-head"><b>${title.textContent}</b><div class="spacer"></div><button class="btn" onclick="billList('${current}')">返回列表</button><button class="btn">保存草稿</button><button class="btn primary" onclick="toast('已提交/审核')">提交/审核</button></div><div class="bill-head-compact"><div class="compact-grid">${headFields.map(f=>`<div class="field"><label>${f}</label>${selectFor(f)}</div>`).join('')}</div></div><div class="detail-actions"><button class="btn primary" onclick="addBillLine()">新增明细行</button><button class="btn">选择商品/来源单据</button><button class="btn">导入明细</button><span class="mini-note">表头已压缩，明细网格铺满展示，不随记录数量收起。</span></div><div class="detail-fill"><table id="billDetail"><tr>${detailHeads.map(h=>`<th>${h}</th>`).join('')}</tr>${Array.from({length:14}).map((_,i)=>`<tr><td contenteditable>${i===0?'示例商品':''}</td><td contenteditable>${i===0?'箱':''}</td><td contenteditable class="num">${i===0?'10':''}</td><td contenteditable class="num">${i===0?'35.00':''}</td><td class="num">${i===0?'350.00':''}</td><td contenteditable class="num">${i===0?'31.2000':''}</td><td class="num">${i===0?'312.00':''}</td><td contenteditable>${i===0?'B202606':''}</td><td contenteditable></td><td><span class="link" onclick="this.closest('tr').remove()">删除</span></td></tr>`).join('')}</table></div><div class="summary bill-edit-summary"><span>数量 <b>100</b></span><span>金额 <b>¥1,000.00</b></span><span>成本 <b>¥800.00</b></span><div style="flex:1"></div><button class="btn primary" onclick="toast('审核完成')">审核</button></div></div>`}'''
s = re.sub(r"function billEdit\(mode\)\{.*?\}\nfunction quick", new_func + "\nfunction quick", s, count=1)
add_func = '''function addBillLine(){let t=document.getElementById('billDetail');if(!t)return;t.insertAdjacentHTML('beforeend',`<tr><td contenteditable>新增商品</td><td contenteditable></td><td contenteditable class="num"></td><td contenteditable class="num"></td><td class="num"></td><td contenteditable class="num"></td><td class="num"></td><td contenteditable></td><td contenteditable></td><td><span class="link" onclick="this.closest('tr').remove()">删除</span></td></tr>`);toast('已新增明细行')}'''
s=s.replace('function newRecord(){', add_func+'function newRecord(){')
p.write_text(s,encoding='utf-8')
