from pathlib import Path
p=Path(r'E:\我的工作项目\erp-wms-tms\prototype\v1-erp-complete\supplier-archive.html')
s=p.read_text(encoding='utf-8')
# add period styles
s=s.replace('.pay-preview{background:#eef6ff;border:1px solid #bfdbfe;color:#1d4ed8;border-radius:8px;padding:12px;margin-top:12px;font-weight:700}', '.pay-preview{background:#eef6ff;border:1px solid #bfdbfe;color:#1d4ed8;border-radius:8px;padding:12px;margin-top:12px;font-weight:700}.period-box{border:1px solid #e5eaf2;border-radius:8px;background:#fbfcfe;padding:18px;margin:12px 0 22px}.period-title{font-size:16px;font-weight:700;margin-bottom:14px}.period-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:22px 54px}.period-grid label{font-weight:700;display:flex;align-items:center;gap:12px}.period-grid input,.period-grid select{height:40px;border:1px solid #dbe3ef;border-radius:5px;padding:0 12px;min-width:170px}.rule-preview{background:#eef6ff;border:1px solid #bfdbfe;color:#1d4ed8;border-radius:8px;padding:12px;margin-top:16px;font-weight:700}.hint{color:#667085;font-size:13px;margin-top:10px}')
# update table header and rows for flexible term
s=s.replace('<th>结算方式</th><th>账期天数</th><th>默认采购员</th>', '<th>结算方式</th><th>账期类型</th><th>账期规则</th><th>默认采购员</th>')
s=s.replace("'月结','30','李四'", "'月结','月结固定付款日','每月25日截账，次月10日付款','李四'")
s=s.replace("'现结','0','李四'", "'现结','现结','到货即付','李四'")
s=s.replace("'月结','30','王五'", "'月结','固定账期天数','收票后30天付款','王五'")
old = '''<section class="section" id="settle"><div class="sec">结算设置</div><div class="form3"><label class="field">结算方式<select><option>月结</option><option>现结</option><option>预付</option></select></label><label class="field">账期天数<input value="30"></label><label class="field">付款条件<input value="到货后30天付款"></label><label class="field">应付余额<input disabled value="6600.00"></label><label class="field">预付余额<input disabled value="1000.00"></label><label class="field">费用余额<input disabled value="0.00"></label></div><div class="pay-preview">付款时可在付款单中选择本供应商的任一正常收款账户；默认带出“默认账户”。</div></section>'''
new = '''<section class="section" id="settle"><div class="sec">结算设置</div><div class="period-box"><div class="period-title">账期基础设置</div><div class="period-grid"><label>是否设账期<select><option>是</option><option>否</option></select></label><label>结算方式<select><option>月结</option><option>固定账期</option><option>现结</option><option>预付</option></select></label><label>付款控制<select><option>提醒</option><option>阻断</option><option>审批</option></select></label><label>账期类型<select id="supplierPeriodType" onchange="supplierPeriodChange()"><option value="supMonthlyFixed">月结固定付款日</option><option value="supMonthlyDays">月结账期天数</option><option value="supHalfMonth">半月结</option><option value="supWeekly">周结</option><option value="supFixedDays">固定账期天数</option></select></label><label>发票要求<select><option>先票后款</option><option>先款后票</option><option>不限制</option></select></label><label>默认付款账户<select><option>默认账户 - 工商银行 6222****0000</option></select></label></div><div class="hint">供应商账期用于采购收货单审核后计算应付预计付款日，并影响付款排期、付款提醒和逾期应付。</div></div><div class="period-box" id="supMonthlyFixed"><div class="period-title">月结固定付款日</div><div class="period-grid"><label>截账日<input value="25"></label><label>付款月<select><option>次月</option><option>当月</option><option>隔月</option></select></label><label>付款日<input value="10"></label></div><div class="rule-preview">示例：6月1日-6月25日收货/收票，统一在7月10日付款。</div></div><div class="period-box" id="supMonthlyDays" style="display:none"><div class="period-title">月结账期天数</div><div class="period-grid"><label>截账日<input value="25"></label><label>账期天数<input value="30"></label><label>起算依据<select><option>收货日期</option><option>发票日期</option><option>对账日期</option></select></label></div><div class="rule-preview">示例：每月25日截账，截账后30天为预计付款日。</div></div><div class="period-box" id="supHalfMonth" style="display:none"><div class="period-title">半月结</div><div class="period-grid"><label>上半月截账日<input value="15"></label><label>下半月截账日<input value="月底"></label><label>付款延后天数<input value="10"></label></div><div class="rule-preview">示例：1-15日收货为上半月账单，延后10天付款。</div></div><div class="period-box" id="supWeekly" style="display:none"><div class="period-title">周结</div><div class="period-grid"><label>截账星期<select><option>星期日</option><option>星期六</option></select></label><label>付款星期<select><option>星期三</option><option>星期五</option></select></label></div><div class="rule-preview">示例：每周日截账，下周三付款。</div></div><div class="period-box" id="supFixedDays" style="display:none"><div class="period-title">固定账期天数</div><div class="period-grid"><label>账期天数<input value="30"></label><label>起算依据<select><option>采购收货审核日</option><option>采购发票日期</option><option>供应商对账日</option></select></label></div><div class="rule-preview">示例：采购收货审核后30天为预计付款日。</div></div><div class="form3"><label class="field">应付余额<input disabled value="6600.00"></label><label class="field">预付余额<input disabled value="1000.00"></label><label class="field">费用余额<input disabled value="0.00"></label></div><div class="pay-preview">付款时可在付款单中选择本供应商的任一正常收款账户；默认带出“默认账户”。</div></section>'''
if old not in s:
    print('settle marker not found')
else:
    s=s.replace(old,new)
# add function before closeM
s=s.replace('function closeM(){mask.classList.remove', "function supplierPeriodChange(){['supMonthlyFixed','supMonthlyDays','supHalfMonth','supWeekly','supFixedDays'].forEach(id=>document.getElementById(id).style.display='none');document.getElementById(document.getElementById('supplierPeriodType').value).style.display='block'}\nfunction closeM(){mask.classList.remove")
p.write_text(s,encoding='utf-8')
