-- ERP-WMS-TMS V1.0 系统底座表
-- 数据库：MySQL 8.x

CREATE TABLE IF NOT EXISTS sys_user (
  user_id VARCHAR(32) PRIMARY KEY COMMENT '用户ID',
  username VARCHAR(50) NOT NULL UNIQUE COMMENT '登录账号',
  password_hash VARCHAR(255) NOT NULL COMMENT '密码Hash',
  display_name VARCHAR(100) NOT NULL COMMENT '用户名称',
  mobile VARCHAR(30) NULL COMMENT '手机号',
  email VARCHAR(100) NULL COMMENT '邮箱',
  status VARCHAR(20) NOT NULL DEFAULT 'NORMAL' COMMENT 'NORMAL/STOPPED/LOCKED',
  last_login_at DATETIME NULL COMMENT '最后登录时间',
  created_by VARCHAR(32) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(32) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT='系统用户';

CREATE TABLE IF NOT EXISTS sys_role (
  role_id VARCHAR(32) PRIMARY KEY COMMENT '角色ID',
  role_code VARCHAR(50) NOT NULL UNIQUE COMMENT '角色编码',
  role_name VARCHAR(100) NOT NULL COMMENT '角色名称',
  status VARCHAR(20) NOT NULL DEFAULT 'NORMAL' COMMENT 'NORMAL/STOPPED',
  remark VARCHAR(500) NULL,
  created_by VARCHAR(32) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(32) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT='权限组/角色';

CREATE TABLE IF NOT EXISTS sys_user_role (
  id VARCHAR(32) PRIMARY KEY,
  user_id VARCHAR(32) NOT NULL,
  role_id VARCHAR(32) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_user_role (user_id, role_id)
) COMMENT='用户角色关系';

CREATE TABLE IF NOT EXISTS sys_menu (
  menu_id VARCHAR(32) PRIMARY KEY,
  parent_id VARCHAR(32) NULL,
  menu_code VARCHAR(100) NOT NULL UNIQUE,
  menu_name VARCHAR(100) NOT NULL,
  route_path VARCHAR(200) NULL,
  component_path VARCHAR(200) NULL,
  menu_type VARCHAR(20) NOT NULL COMMENT 'DIR/MENU/BUTTON',
  permission_code VARCHAR(100) NULL,
  sort_no INT NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT='系统菜单与按钮权限';

CREATE TABLE IF NOT EXISTS sys_role_permission (
  id VARCHAR(32) PRIMARY KEY,
  role_id VARCHAR(32) NOT NULL,
  menu_id VARCHAR(32) NOT NULL,
  permission_code VARCHAR(100) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_role_menu (role_id, menu_id)
) COMMENT='角色菜单权限';

CREATE TABLE IF NOT EXISTS sys_param (
  param_id VARCHAR(32) PRIMARY KEY,
  param_key VARCHAR(100) NOT NULL UNIQUE,
  param_name VARCHAR(100) NOT NULL,
  param_value VARCHAR(500) NULL,
  default_value VARCHAR(500) NULL,
  param_group VARCHAR(50) NOT NULL,
  param_type VARCHAR(20) NOT NULL COMMENT 'TEXT/NUMBER/BOOLEAN/SELECT/DATE',
  remark VARCHAR(500) NULL,
  updated_by VARCHAR(32) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT='系统参数';

CREATE TABLE IF NOT EXISTS sys_bill_no_rule (
  rule_id VARCHAR(32) PRIMARY KEY,
  bill_type VARCHAR(100) NOT NULL UNIQUE,
  prefix VARCHAR(20) NOT NULL,
  date_format VARCHAR(30) NOT NULL DEFAULT 'yyyyMMdd',
  serial_length INT NOT NULL DEFAULT 4,
  reset_cycle VARCHAR(20) NOT NULL DEFAULT 'DAY' COMMENT 'DAY/MONTH/YEAR/NEVER',
  example_no VARCHAR(100) NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
  updated_by VARCHAR(32) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT='单据编号规则';

CREATE TABLE IF NOT EXISTS sys_operation_log (
  log_id VARCHAR(32) PRIMARY KEY,
  module_code VARCHAR(100) NOT NULL,
  biz_type VARCHAR(100) NULL,
  biz_id VARCHAR(32) NULL,
  biz_no VARCHAR(100) NULL,
  action VARCHAR(50) NOT NULL,
  operator_id VARCHAR(32) NOT NULL,
  operator_name VARCHAR(100) NOT NULL,
  operate_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  result VARCHAR(20) NOT NULL COMMENT 'SUCCESS/FAIL',
  detail TEXT NULL
) COMMENT='操作日志';
