-- V41: fin_ar 增加对账状态 + 创建时间
ALTER TABLE fin_ar ADD COLUMN IF NOT EXISTS reconcile_status VARCHAR(20) DEFAULT '未对账';
ALTER TABLE fin_ar ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
