export const fallbackMenus = {
  首页: [{ code: 'dashboard', name: '经营概览' }],
  基础资料: [
    { code: 'goods', name: '商品档案' },
    { code: 'category', name: '商品分类' },
    { code: 'brand', name: '品牌管理' },
    { code: 'unit', name: '单位管理' },
    { code: 'customer', name: '门店/客户资料' },
    { code: 'supplier', name: '供应商资料' },
    { code: 'warehouse', name: '仓库资料' },
    { code: 'priceGroup', name: '价格组设置' },
    { code: 'customerPrice', name: '客户价格调整单' },
    { code: 'customerPriceQuery', name: '客户价格查询' },
    { code: 'territory', name: '片区管理' },
    { code: 'routeLine', name: '线路管理' },
    { code: 'employee', name: '人员信息' },
    { code: 'department', name: '部门管理' },
    { code: 'owner', name: '货主信息' },
    { code: 'expenseType', name: '费用类型' },
    { code: 'counterparty', name: '往来单位' },
    { code: 'fundAccount', name: '资金账户' },
  ],
  采购管理: [
    { code: 'purchaseOrder', name: '采购订单' },
    { code: 'purchaseInbound', name: '采购入库' },
    { code: 'purchaseReceipt', name: '采购收货单' },
    { code: 'purchaseReturn', name: '采购退货单' },
    { code: 'purchaseExpense', name: '采购费用单' },
    { code: 'purchaseInvoice', name: '采购发票' },
  ],
  销售管理: [
    { code: 'quickOrder', name: '销售快速开单' },
    { code: 'salesOrder', name: '销售订单' },
    { code: 'salesOutbound', name: '销售出库' },
    { code: 'salesReceipt', name: '销售收货单' },
    { code: 'salesReturn', name: '销售退货单' },
    { code: 'salesInvoice', name: '销售发票' },
    { code: 'flyOrder', name: '飞单' },
    { code: 'emptyAdjust', name: '客户空退空出' },
  ],
  库存管理: [
    { code: 'stockBalance', name: '库存余额' },
    { code: 'stockLedger', name: '库存流水' },
    { code: 'stockLock', name: '库存锁定' },
    { code: 'batchStock', name: '批次库存' },
    { code: 'stockWarning', name: '库存预警' },
    { code: 'transfer', name: '调拨单' },
    { code: 'damage', name: '报损单' },
    { code: 'costAdjust', name: '成本调整单' },
    { code: 'stockAdjust', name: '库存调整单' },
    { code: 'otherInbound', name: '其他入库' },
    { code: 'otherOutbound', name: '其他出库' },
    { code: 'stockTake', name: '库存盘点' },
  ],
  财务管理: [
    { code: 'ar', name: '应收账款' },
    { code: 'ap', name: '应付账款' },
    { code: 'receiptPayment', name: '收付款单' },
    { code: 'arSettlement', name: '应收结算' },
    { code: 'apSettlement', name: '应付结算' },
    { code: 'financeExpense', name: '费用单' },
    { code: 'fundLedger', name: '资金流水' },
    { code: 'counterpartyAr', name: '往来单位应收' },
    { code: 'counterpartyAp', name: '往来单位应付' },
    { code: 'receiptVerify', name: '收款核销' },
    { code: 'paymentVerify', name: '付款核销' },
    { code: 'customerStatement', name: '客户对账' },
    { code: 'supplierStatement', name: '供应商对账' },
  ],
  报表中心: [
    { code: 'chartReport', name: '图表报表' },
    { code: 'salesReport', name: '销售报表' },
    { code: 'purchaseReport', name: '采购报表' },
    { code: 'stockReport', name: '库存报表' },
    { code: 'financeReport', name: '财务报表' },
  ],
  系统管理: [
    { code: 'user', name: '用户管理' },
    { code: 'role', name: '权限组管理' },
    { code: 'param', name: '系统参数' },
    { code: 'billNo', name: '单据编号规则' },
    { code: 'precision', name: '显示精度设置' },
    { code: 'dictionary', name: '用户数据字典' },
    { code: 'workflow', name: '审批流配置' },
    { code: 'printTemplate', name: '打印模板设置' },
    { code: 'importList', name: '导入列表' },
    { code: 'exportCenter', name: '导出中心' },
    { code: 'log', name: '操作日志' },
  ],
  工作台: [
    { code: 'todo', name: '待办中心' },
    { code: 'notification', name: '消息通知' },
  ],
}
