export const moduleApis = {
  goods: { page: '/base/goods/page', save: '/base/goods/create', update: '/base/goods/update', stop: '/base/goods/stop', delete: '/base/goods/delete' },
  category: { page: '/base/category/page', save: '/base/category/create', update: '/base/category/update', stop: '/base/category/stop', delete: '/base/category/delete' },
  brand: { page: '/base/brand/page', save: '/base/brand/create', update: '/base/brand/update', stop: '/base/brand/stop', delete: '/base/brand/delete' },
  unit: { page: '/base/unit/page', save: '/base/unit/create', update: '/base/unit/update', stop: '/base/unit/stop', delete: '/base/unit/delete' },
  warehouse: { page: '/base/warehouse/page', save: '/base/warehouse/create', update: '/base/warehouse/update', stop: '/base/warehouse/stop', delete: '/base/warehouse/delete' },
  customer: { page: '/base/customer/page', save: '/base/customer/create', update: '/base/customer/update', stop: '/base/customer/stop', delete: '/base/customer/delete' },
  supplier: { page: '/base/supplier/page', save: '/base/supplier/create', update: '/base/supplier/update', stop: '/base/supplier/stop', delete: '/base/supplier/delete' },
  priceGroup: { page: '/base/master/price-group/page', save: '/base/master/save', stop: '/base/master/stop', delete: '/base/master/delete', enable: '/base/master/price-group/enable', customers: '/base/master/price-group/customers' },
  priceGroupItem: { page: '/base/price-group-item/page', toggle: '/base/price-group-item/toggle' },
  priceAdjustOrder: { page: '/base/price-adjust-order/page', save: '/base/price-adjust-order/save', detail: '/base/price-adjust-order/detail', submit: '/base/price-adjust-order/submit', audit: '/base/price-adjust-order/approve', reject: '/base/price-adjust-order/reject', delete: '/base/price-adjust-order/delete' },
  goodsPriceAdjust: { page: '/base/goods-price-adjust/page', save: '/base/goods-price-adjust/save', detail: '/base/goods-price-adjust/detail', submit: '/base/goods-price-adjust/submit', audit: '/base/goods-price-adjust/approve', confirm: '/base/goods-price-adjust/confirm', reject: '/base/goods-price-adjust/reject', delete: '/base/goods-price-adjust/delete' },
  priceChangeLog: { page: '/base/price-change-log/page' },
  counterparty: { page: '/base/master/counterparty/page', save: '/base/master/save', stop: '/base/master/stop', delete: '/base/master/delete', tree: '/base/master/counterparty/tree' },
  counterpartyType: { page: '/base/master/counterparty-type/page', save: '/base/master/save', stop: '/base/master/stop', delete: '/base/master/delete' },
  fundAccount: { page: '/base/master/fund-account/page', save: '/base/master/save', stop: '/base/master/stop', delete: '/base/master/delete' },
  expenseType: { page: '/base/master/expense-type/page', save: '/base/master/save', stop: '/base/master/stop', delete: '/base/master/delete' },
  territory: { page: '/base/master/territory/page', save: '/base/master/save', stop: '/base/master/stop', delete: '/base/master/delete' },
  routeLine: { page: '/base/master/route-line/page', save: '/base/master/save', stop: '/base/master/stop', delete: '/base/master/delete' },
  employee: { page: '/base/master/employee/page', save: '/base/master/save', stop: '/base/master/stop', delete: '/base/master/delete' },
  department: { page: '/base/master/department/page', save: '/base/master/save', stop: '/base/master/stop', delete: '/base/master/delete' },
  owner: { page: '/base/master/owner/page', save: '/base/master/save', stop: '/base/master/stop', delete: '/base/master/delete' },

  customerPrice: { page: '/base/customer-price-adjust/page', save: '/base/customer-price-adjust/create', audit: '/base/customer-price-adjust/audit', cancel: '/base/customer-price-adjust/cancel', import: '/base/customer-price-adjust/import' },
  customerPriceQuery: { page: '/base/customer-price/query', stop: '/base/customer-price/stop' },
  customerPriceChangeLog: { page: '/base/customer-price-change-log/page' },

  stockBalance: { page: '/inventory/balance/page' },
  stockLedger: { page: '/inventory/ledger/page' },
  stockLock: { page: '/inventory/lock/page' },
  batchStock: { page: '/inventory/batch/page' },
  stockWarning: { page: '/inventory/warning/page' },
  transferApply: { page: '/transfer/apply/page', save: '/transfer/apply/create', update: '/transfer/apply/update', detail: '/transfer/apply/detail', delete: '/transfer/apply/delete', audit: '/transfer/apply/audit', reverseAudit: '/transfer/apply/reverse-audit' },
  transferOutbound: { page: '/transfer/outbound/page', save: '/transfer/outbound/create', detail: '/transfer/outbound/detail', fromApply: '/transfer/outbound/from-apply', update: '/transfer/outbound/update', audit: '/transfer/outbound/audit', reverseAudit: '/transfer/outbound/reverse-audit' },
  transferInbound: { page: '/transfer/inbound/page', detail: '/transfer/inbound/detail', audit: '/transfer/inbound/audit', reverseAudit: '/transfer/inbound/reverse-audit' },
  damage: { page: '/inventory/damage/page', create: '/inventory/damage/create', update: '/inventory/damage/update', detail: '/inventory/damage/detail', audit: '/inventory/damage/audit', reverseAudit: '/inventory/damage/reverse-audit', delete: '/inventory/damage/delete', cancel: '/inventory/damage/cancel', import: '/inventory/damage/import', goodsOptions: '/inventory/damage/goods-options', batchOptions: '/inventory/damage/batch-options', batchStockOptions: '/inventory/damage/batch-stock-options' },
  costAdjust: { page: '/inventory/cost-adjust/page', audit: '/inventory/cost-adjust/audit' },
  stockAdjust: { page: '/inventory/cost-adjust/page', audit: '/inventory/cost-adjust/audit' },
  otherInbound: { page: '/inventory/other-inbound/page', save: '/inventory/other-inbound/create', update: '/inventory/other-inbound/update', detail: '/inventory/other-inbound/detail', audit: '/inventory/other-inbound/audit', reverseAudit: '/inventory/other-inbound/reverse-audit', delete: '/inventory/other-inbound/delete', cancel: '/inventory/other-inbound/cancel', import: '/inventory/other-inbound/import', goodsOptions: '/inventory/other-inbound/goods-options', batchOptions: '/inventory/other-inbound/batch-options' },
  otherOutbound: { page: '/inventory/other-outbound/page', save: '/inventory/other-outbound/create', update: '/inventory/other-outbound/update', detail: '/inventory/other-outbound/detail', audit: '/inventory/other-outbound/audit', reverseAudit: '/inventory/other-outbound/reverse-audit', delete: '/inventory/other-outbound/delete', cancel: '/inventory/other-outbound/cancel', import: '/inventory/other-outbound/import', goodsOptions: '/inventory/other-outbound/goods-options', batchOptions: '/inventory/other-outbound/batch-options', batchStockOptions: '/inventory/other-outbound/batch-stock-options' },
  stockTake: { page: '/inventory/stock-take/page', save: '/inventory/stock-take/create', detail: '/inventory/stock-take/detail', update: '/inventory/stock-take/update-real', audit: '/inventory/stock-take/audit', reverseAudit: '/inventory/stock-take/reverse-audit', delete: '/inventory/stock-take/delete', parseItems: '/inventory/stock-take/parse-items', parseExcel: '/inventory/stock-take/parse-excel', exportDetail: '/inventory/stock-take/export-detail', importReal: '/inventory/stock-take/import-real' },

  purchaseOrder: { page: '/purchase/order/page', save: '/purchase/order/create', update: '/purchase/order/update', detail: '/purchase/order/detail', audit: '/purchase/order/audit', reverseAudit: '/purchase/order/reverse-audit', close: '/purchase/order/close', delete: '/purchase/order/delete' },
  purchaseInbound: { page: '/purchase/inbound/page', save: '/purchase/inbound/create', detail: '/purchase/inbound/detail', audit: '/purchase/inbound/audit' },
  purchaseReceipt: { page: '/purchase/receipt/page', detail: '/purchase/receipt/detail', update: '/purchase/receipt/update', audit: '/purchase/receipt/audit', reverseAudit: '/purchase/receipt/reverse-audit' },
  purchaseReturnApply: { page: '/purchase/return-apply/page', save: '/purchase/return-apply/create', update: '/purchase/return-apply/update', detail: '/purchase/return-apply/detail', audit: '/purchase/return-apply/audit', reverseAudit: '/purchase/return-apply/reverse-audit', delete: '/purchase/return-apply/delete' },
  purchaseReturnOutbound: { page: '/purchase/return-outbound/page', detail: '/purchase/return-outbound/detail', update: '/purchase/return-outbound/update', audit: '/purchase/return-outbound/audit' },
  purchaseReturn: { page: '/purchase/return/page', detail: '/purchase/return/detail', audit: '/purchase/return/audit', reverseAudit: '/purchase/return/reverse-audit' },
  purchaseExpense: { page: '/purchase/expense/page', audit: '/purchase/expense/audit' },
  purchaseInvoice: { page: '/purchase/invoice/page' },

  quickOrder: { page: '/sales/order/page', save: '/sales/quick-order/create-and-audit', audit: '/sales/quick-order/create-and-audit' },
  salesOrder: { page: '/sales/order/page', save: '/sales/order/create', update: '/sales/order/update', detail: '/sales/order/detail', audit: '/sales/order/audit', reverseAudit: '/sales/order/reverse-audit', close: '/sales/order/close', delete: '/sales/order/delete' },
  salesOutbound: { page: '/sales/outbound/page', save: '/sales/outbound/create', detail: '/sales/outbound/detail', audit: '/sales/outbound/audit' },
  salesReceipt: { page: '/sales/receipt/page', detail: '/sales/receipt/detail', audit: '/sales/receipt/audit', reverseAudit: '/sales/receipt/reverse-audit', sign: '/sales/receipt/sign', unsign: '/sales/receipt/unsign' },
  // 拒收入库单：故意不配 save/create —— 只能由发货单签收拒收自动生成
  rejectInbound: { page: '/sales/reject-inbound/page', detail: '/sales/reject-inbound/detail', update: '/sales/reject-inbound/update', audit: '/sales/reject-inbound/audit', reverseAudit: '/sales/reject-inbound/reverse-audit', batchOptions: '/sales/reject-inbound/batch-options' },
  salesReturn: { page: '/sales/return-order/page', save: '/sales/return-order/create', update: '/sales/return-order/update', detail: '/sales/return-order/detail', audit: '/sales/return-order/audit', reverseAudit: '/sales/return-order/reverse-audit', confirm: '/sales/return-order/confirm', reject: '/sales/return-order/reject', delete: '/sales/return-order/delete' },
  salesReturnInbound: { page: '/sales/return-inbound/page', detail: '/sales/return-inbound/detail', update: '/sales/return-inbound/update', audit: '/sales/return-inbound/audit' },
  salesInvoice: { page: '/sales/invoice/page' },
  flyOrder: { page: '/sales/fly-order/page', create: '/sales/fly-order/create', update: '/sales/fly-order/update', detail: '/sales/fly-order/detail', audit: '/sales/fly-order/audit', reverseAudit: '/sales/fly-order/unaudit', cancel: '/sales/fly-order/cancel', delete: '/sales/fly-order/delete', batchAudit: '/sales/fly-order/batch-audit', batchUnaudit: '/sales/fly-order/batch-unaudit', batchDelete: '/sales/fly-order/batch-delete', exportAll: '/sales/fly-order/export', exportDetail: '/sales/fly-order/export-detail' },
  emptyAdjust: { page: '/sales/empty-adjust/page', audit: '/flow/v1-core/self-test' },

  ar: { page: '/finance/ar/page', settle: '/finance/ar/settle' },
  ap: { page: '/finance/ap/page', reconcile: '/finance/reconcile/pay' },
  receiptPayment: { page: '/finance/receipt/page', save: '/finance/receipt/create', audit: '/finance/receipt/audit', batchAudit: '/finance/receipt/batch-audit' },
  paymentModule: { page: '/finance/payment/page', save: '/finance/payment/create', audit: '/finance/payment/audit', batchAudit: '/finance/payment/batch-audit' },
  reconcileRecord: { page: '/finance/reconcile-record/page' },
  arSettlement: { page: '/finance/ar-settlement/page', reconcile: '/finance/reconcile/receive' },
  apSettlement: { page: '/finance/ap-settlement/page', reconcile: '/finance/reconcile/pay' },
  financeExpense: { page: '/finance/expense/page', save: '/finance/expense/create', audit: '/finance/expense/audit' },
  fundLedger: { page: '/finance/fund-ledger/page' },
  counterpartyAr: { page: '/finance/ar/page', reconcile: '/finance/reconcile/receive' },
  counterpartyAp: { page: '/finance/ap/page', reconcile: '/finance/reconcile/pay' },
  receiptVerify: { page: '/finance/ar/page', reconcile: '/finance/reconcile/receive' },
  paymentVerify: { page: '/finance/ap/page', reconcile: '/finance/reconcile/pay' },
  customerStatement: { page: '/finance/customer-statement/page', save: '/finance/customer-statement/create', audit: '/finance/customer-statement/audit' },
  supplierStatement: { page: '/finance/supplier-statement/page', save: '/finance/supplier-statement/create', audit: '/finance/supplier-statement/audit' },

  user: { page: '/system/user/page', save: '/system/user/save', stop: '/base/master/stop' },
  role: { page: '/system/role/page', save: '/system/role/save', stop: '/base/master/stop' },
  param: { page: '/system/param/page', save: '/system/param/update' },
  billNo: { page: '/system/bill-no-rule/page', save: '/system/bill-no-rule/update' },
  precision: { page: '/system/precision/page', save: '/system/precision/save' },
  dictionary: { page: '/system/dictionary/page', save: '/system/dictionary/save' },
  workflow: { page: '/system/workflow/page', save: '/system/workflow/save' },
  printTemplate: { page: '/system/print-template/page', save: '/system/print-template/save' },
  importList: { page: '/system/import-list/page', import: '/system/import-list/create', download: '/system/import-list/download-failures' },
  exportCenter: { page: '/system/export-center/page', download: '/system/export-center/download' },
  log: { page: '/system/operation-log/page' },

  salesReport: { page: '/report/sales/page', export: '/excel/export/salesOrder' },
  purchaseReport: { page: '/report/purchase/page', export: '/excel/export/purchaseOrder' },
  stockReport: { page: '/report/stock/page', export: '/excel/export/stockBalance' },
  financeReport: { page: '/report/finance/page', export: '/excel/export/finance' },
}

export const excelModules = {
  goods: { export: '/excel/export/goods', import: '/excel/import/goods', template: '/excel/template/goods' },
  customer: { export: '/excel/export/customer', import: '/excel/import/customer', template: '/excel/template/customer' },
  supplier: { export: '/excel/export/supplier', import: '/excel/import/supplier', template: '/excel/template/supplier' },
  warehouse: { export: '/excel/export/warehouse', import: '/excel/import/warehouse', template: '/excel/template/warehouse' },
  purchaseOrder: { export: '/excel/export/purchaseOrder', import: '/excel/import/purchaseOrder', template: '/excel/template/purchaseOrder' },
  salesOrder: { export: '/excel/export/salesOrder', import: '/excel/import/salesOrder', template: '/excel/template/salesOrder' },
  expenseType: { export: '/excel/export/expenseType', import: '/excel/import/expenseType', template: '/excel/template/expenseType' },
}

import { autoFormatByTitle } from './utils/dateTime.js'

export function mapRecordToRow(record, config) {
  const row = Object.fromEntries(config.columns.map((title, index) => {
    const raw = valueForTitle(title, record)
    return [`c${index}`, autoFormatByTitle(title, raw)]
  }))
  row._raw = record
  return row
}

// ============================================================
// 列标题 -> 后端字段名 精确映射表
// 顺序：先精确匹配（如"分类名称"），再宽泛匹配（如"名称"）
// ============================================================
const EXACT_TITLE_MAP = {
  // 商品
  '商品图片': ['image'],
  '商品编码': ['goodsCode', 'code'],
  '商品编号': ['goodsCode', 'code'],
  '商品': ['goodsName', 'goodsCode'],
  '商品名称': ['goodsName'],
  '商品类型': ['goodsType'],
  '商品等级': ['goodsLevel'],
  '商品简介': ['goodsIntro'],
  '规格': ['spec'],
  '规格型号': ['spec'],
  '简拼': ['simpleCode'],
  '简码': ['simpleCode'],
  '条码': ['barcode'],
  '基本单位': ['baseUnit'],
  '税率': ['taxRate'],
  '存储属性': ['storageProperty'],
  '产地': ['origin'],
  '保质期': ['shelfLifeDays'],
  '临期预警天数': ['warningDays'],
  '库存上限': ['stockUpperLimit'],
  '库存下限': ['stockLowerLimit'],
  '采购起订量': ['minOrderQty'],
  '标准售价': ['standardPrice'],
  '建议零售价': ['suggestedRetailPrice'],
  '参考进价': ['latestPurchasePrice', 'referencePurchasePrice'],
  '最新进价': ['latestPurchasePrice'],
  '最低售价': ['minSalePrice'],
  '默认供应商': ['defaultSupplier'],
  '主供应商': ['defaultSupplier'],
  '默认仓库': ['defaultWarehouse'],
  '当前库存': ['currentStock', 'physicalQty'],
  '实物库存': ['physicalQty', 'currentStock'],
  '可用库存': ['availableQty'],
  '锁定库存': ['lockedQty'],
  '冻结库存': ['frozenQty'],
  '库存金额': ['stockAmount'],
  '成本单价': ['costPrice'],
  '采购在途': ['purchaseOnWay'],
  '最近出入库时间': ['lastInoutTime'],
  '方向': ['direction'],
  '变动后数量': ['balanceQty'],
  '成本价': ['costPrice'],
  '成本金额': ['costAmount'],
  '可售/可采购': ['salePurchaseFlag'],
  '可售/可采购/可退': ['salePurchaseReturnFlag'],
  '商品负责人': ['goodsManager'],
  '采购负责人': ['goodsManager'],

  // 库存件数（大单位换算后派生字段）
  '实物库存件数': ['physicalQtyPieces'],
  '锁定件数': ['lockedQtyPieces'],
  '冻结件数': ['frozenQtyPieces'],
  '可用件数': ['availableQtyPieces'],
  '可用库存金额': ['availableStockAmount'],
  '商品分类条码': ['barcode'],

  // 商品分类
  '分类编码': ['categoryCode'],
  '分类名称': ['categoryName'],
  '分类': ['categoryName', 'category'],
  '上级分类': ['parentName', 'parentCode', 'parentId'],
  '默认税率': ['defaultTaxRate'],
  '商品数': ['goodsCount'],
  '外部编码': ['externalCode'],

  // 品牌
  '品牌编码': ['brandCode'],
  '品牌名称': ['brandName'],
  '品牌': ['brandName'],

  // 单位
  '单位编码': ['unitCode'],
  '单位名称': ['unitName'],
  '单位': ['unitName', 'baseUnit', 'unit'],
  '可作为基本单位': ['canBaseUnit'],
  '是否中单位': ['canMiddleUnit'],
  '是否大单位': ['canLargeUnit'],

  // 仓库
  '仓库编码': ['warehouseCode'],
  '仓库名称': ['warehouseName'],
  '仓库类型': ['warehouseType'],
  '存货类型': ['inventoryType'],
  '库存类型': ['inventoryType'],
  '成本分组': ['costGroup'],
  '负责人': ['managerName'],
  '仓库': ['warehouse', 'warehouseName'],
  '收货仓库': ['warehouse'],
  '入库仓库': ['warehouse'],
  '出库仓库': ['warehouse'],
  '调出仓库': ['warehouseOut'],
  '调入仓库': ['warehouseIn'],
  '地址': ['address'],
  '货主': ['ownerName'],
  '是否默认': ['isDefault'],

  // 客户
  '客户编码': ['customerCode'],
  '客户名称': ['customerName'],
  '客户编号/名称': ['customerName'],
  '客户': ['customerName', 'customer'],
  '门店': ['customerName'],
  '渠道类型': ['channelType'],
  '客户等级': ['customerLevel'],
  '账期类型': ['accountPeriodType'],
  '截账日': ['cutoffDay'],
  '付款日': ['paymentDay'],
  '信用额度': ['creditLimit'],
  '应收余额': ['arBalance'],
  '逾期金额': ['overdueAmount'],
  '发票抬头': ['invoiceTitle'],
  '税号': ['taxNo'],
  '交货方式': ['deliveryMethod'],
  '默认物流公司': ['defaultLogisticsCompany'],

  // 供应商
  '供应商编码': ['supplierCode'],
  '供应商名称': ['supplierName'],
  '供应商简称': ['shortName'],
  '供应商类型': ['supplierType'],
  '供应商': ['supplierName', 'supplier'],
  '简称': ['shortName'],
  '类型': ['type', 'supplierType'],
  '电话': ['phone'],
  '到货天数': ['deliveryDays'],
  '结算方式': ['settlementText', 'settlementMethod'],
  '收货地址': ['shippingAddress'],
  '账期天数': ['accountPeriodDays'],
  '默认采购员': ['defaultBuyer'],
  '默认收款账户': ['defaultReceiptAccount'],
  '应付余额': ['apBalance'],

  // 联系
  '联系人': ['contactName'],
  '手机': ['mobile'],
  '手机号': ['mobile'],

  // 片区/线路/人员/部门/货主
  '片区': ['territory'],
  '片区编码': ['territoryCode'],
  '片区名称': ['territoryName'],
  '上级片区': ['parentName', 'parentCode'],
  '所属城市': ['city'],
  '线路': ['routeLine'],
  '线路编码': ['routeLineCode'],
  '线路名称': ['routeLineName'],
  '司机': ['driver'],
  '默认司机': ['driver'],
  '覆盖范围': ['coverage'],
  '业务员': ['salesman'],
  '采购员': ['buyer'],
  '人员编码': ['employeeCode'],
  '人员姓名': ['employeeName'],
  '姓名': ['employeeName', 'displayName'],
  '性别': ['gender'],
  '身份证号': ['idCard'],
  '学历': ['education'],
  '联系地址': ['address'],
  '所属货主': ['ownerName'],
  '所属部门': ['department'],
  '是否业务员': ['isSalesman'],
  '是否业务员管理员': ['isSalesmanAdmin'],
  '业务员管理员': ['isSalesmanAdmin'],
  '上级业务员': ['parentSalesman'],
  '是否采购员': ['isBuyer'],
  '是否库管员': ['isWarehouseKeeper'],
  '是否配送员': ['isDeliveryman'],
  '职位': ['position'],
  '部门编码': ['departmentCode'],
  '部门名称': ['departmentName'],
  '上级部门': ['parentName'],
  '人数': ['headCount'],
  '货主编码': ['ownerCode'],
  '货主名称': ['ownerName'],
  '货主类型': ['ownerType'],
  '所属平台': ['platform'],

  // 费用类型/往来单位/资金账户/价格组
  '费用类型编码': ['expenseTypeCode'],
  '费用类型名称': ['expenseTypeName'],
  '上级费用类型': ['parentName', 'parentCode'],
  '费用方向': ['direction'],
  '成本参与': ['costParticipation'],
  '往来单位编码': ['counterpartyCode'],
  '往来单位名称': ['counterpartyName'],
  '往来单位': ['counterpartyName'],
  '单位类型': ['counterpartyType', 'typeName'],
  '编号': ['typeCode', 'code'],
  '类型编码': ['typeCode'],
  '类型名称': ['typeName'],
  '账户编码': ['fundAccountCode'],
  '账户名称': ['fundAccountName'],
  '账户类型': ['accountType'],
  '期初余额': ['balance'],
  '上级账户': ['parentName', 'parentCode'],
  '价格组编码': ['priceGroupCode'],
  '价格组名称': ['priceGroupName'],
  '价格组': ['priceGroupName', 'priceGroupCode'],
  '经度': ['longitude'],
  '纬度': ['latitude'],
  '关联客户': ['customerCount'],
  '价格组商品数': ['goodsCount'],
  '是否启用': ['enabled'],
  '排序': ['sortOrder'],

  // 价格组调价单 / 变价日志
  '调价单号': ['orderNo'],
  '单位级别': ['unitLevelText', 'unitLevel'],
  '单位类型': ['unitLevelText', 'unitLevel'],
  '标价': ['standardPrice'],
  '售价': ['price'],
  '变价前': ['oldPriceText', 'oldPrice'],
  '变价后': ['newPrice'],
  '变动幅度': ['changeRateText'],
  '变更类型': ['changeTypeText', 'changeType'],
  '变价时间': ['createdAt'],
  '制单人': ['creatorName', 'createUser'],
  '制单时间': ['createTime'],
  '审核人': ['auditorName', 'auditUser'],
  '审核时间': ['auditTime'],
  '收款单号': ['receiptNo'],
  '付款单号': ['paymentNo'],
  '收款日期': ['receiptDate'],
  '付款日期': ['paymentDate'],
  '往来单位类型': ['counterpartyTypeText', 'counterpartyType'],
  '往来单位编码': ['counterpartyCode'],
  '往来单位名称': ['counterpartyName'],
  '往来单位': ['counterpartyName'],
  '收款金额': ['totalAmount', 'amount'],
  '付款金额': ['totalAmount', 'amount'],
  '核销金额': ['verifiedAmount'],
  '经手人': ['handler'],
  '业务来源': ['businessSourceText', 'businessSource'],
  '关联单号': ['relatedBillNo'],
  '摘要': ['summary'],
  '对账单号': ['statementNo'],
  '客户编号': ['customerCode'],
  '供应商编号': ['supplierCode'],
  '对账日期': ['statementDate'],
  '预计回款日': ['expectedPayDate'],
  '对账金额': ['totalAmount'],
  '已收款金额': ['paidAmount'],
  '已付款金额': ['paidAmount'],
  '抹零金额': ['writeOffAmount'],
  '收款状态': ['payStatus'],
  '是否开票': ['isInvoiced'],
  '出库单号': ['sourceOutboundNo', 'sourceBill'],
  '销售单号': ['sourceOrderNo', 'orderNo', 'salesOrderNo'],
  '客户编号': ['customerCode'],
  '仓库': ['warehouse'],
  '签收日期': ['receiptDate'],
  '商品金额': ['goodsAmount'],
  '税额': ['taxAmount'],
  '费用金额': ['expenseAmount'],
  '最终金额': ['finalAmount'],
  '应收生成': ['arStatusText', 'arStatus'],
  '结算状态': ['receiveStatusText', 'receiveStatus'],
  '签收状态': ['receiveStatusText', 'receiveStatus'],
  '创建人': ['creatorName'],
  '审核人': ['auditUser'],

  // 单据类
  '采购单号': ['orderNo', 'sourceOrder'],
  '订单号': ['orderNo'],
  '入库单号': ['inboundNo'],
  '收货单号': ['receiptNo'],
  '发货单号': ['receiptNo', 'sourceReceiptNo'],
  '出库单号': ['outboundNo', 'sourceOutboundNo'],
  '流水号': ['ledgerNo'],
  '应收单号': ['arNo'],
  '应付单号': ['apNo'],
  '调整单号': ['adjustNo'],
  '退货单号': ['returnNo', 'applyNo'],
  '报损单号': ['damageNo'],
  '申请单号': ['applyNo'],
  '来源收货单': ['sourceReceiptNo'],
  '退货方式': ['returnModeText', 'returnMode'],
  '源单号': ['sourceInboundNo'],
  '源行号': ['sourceDetailId'],
  '可退数量': ['returnableQty'],
  '来源申请单': ['sourceApplyNo'],
  '来源退货单': ['sourceApplyNo'],
  '来源出库单': ['sourceOutboundNo'],
  '发票号码': ['invoiceNo'],
  '费用单号': ['expenseNo'],
  '调拨单号': ['transferNo'],
  '调拨申请单号': ['applyNo'],
  '调拨出库单号': ['outboundNo'],
  '调拨入库单号': ['inboundNo'],
  '转出仓库': ['sourceWarehouse'],
  '调入仓库': ['targetWarehouse'],
  '转入仓库': ['targetWarehouse'],
  '调出仓': ['sourceWarehouse'],
  '调入仓': ['targetWarehouse'],
  '入库类型': ['inboundType'],
  '其他入库类型': ['inboundType'],
  '出库类型': ['outboundType'],
  '其他出库类型': ['outboundType'],
  // 其他入库单/其他出库单：客户与供应商二选一，后端合并成 counterpartyName 供列表展示
  '客户/供应商': ['counterpartyName'],
  '申请数量': ['qty'],
  '出库数量': ['qty'],
  '入库数量': ['qty'],
  '申请日期': ['applyDate', 'billDate'],
  '调拨状态': ['transferStatus'],
  '创建时间': ['createTime', 'createdAt'],
  '审核人': ['auditorName'],
  '收付款单号': ['paymentNo'],
  '单号': ['orderNo', 'billNo', 'inboundNo'],
  '飞单号': ['flyNo'],
  '关联采购单': ['purchaseOrderNo'],
  '关联销售单': ['salesOrderNo'],
  '来源单据': ['sourceBill'],
  '来源销售发货单': ['sourceBill'],
  '来源采购收货单': ['sourceBill'],
  '来源入库单': ['sourceBill', 'sourceReceiptNo', 'sourceInboundNo'],
  '来源销售单号': ['sourceBill'],
  '销售单号': ['sourceOrder', 'orderNo', 'sourceOrderNo'],
  '来源采购单号': ['sourceOrder'],

  '单据日期': ['billDate'],
  '日期': ['billDate'],
  '入库日期': ['billDate'],
  '出库日期': ['billDate'],
  '退货日期': ['returnDate', 'billDate'],
  '签收日期': ['billDate'],
  '发生时间': ['occurredAt'],
  '发生日期': ['occurredAt'],
  '开票日期': ['billDate'],
  '预计到货日期': ['expectedArrivalDate'],
  '预计收款日': ['dueDate'],
  '预计付款日': ['dueDate'],
  '预计日期': ['dueDate'],

  '订单金额': ['amount'],
  '已入库金额': ['inboundAmount'],
  '已出库金额': ['outboundAmount'],
  '应收金额': ['arAmount', 'amount'],
  '应付金额': ['apAmount', 'amount'],
  '销售金额': ['salesAmount', 'amount'],
  '出库金额': ['amount'],
  '出库商品数': ['skuCount'],
  '件数': ['pieceCount'],
  '采购金额': ['purchaseAmount', 'amount'],
  // signAmount 优先给销售发货单（签收后由明细汇总），signedAmount 是 TMS 签收记录的字段名
  '签收金额': ['signAmount', 'signedAmount', 'amount'],
  '入库金额': ['inboundAmount', 'amount'],
  '费用金额': ['expenseAmount', 'amount'],
  '退货金额': ['amount'],
  '金额': ['amount'],
  '销售总额': ['salesAmount', 'amount'],
  '已收金额': ['receivedAmount', 'paidAmount'],
  '已收': ['receivedAmount'],
  '未收金额': ['unreceivedAmount', 'unpaidAmount'],
  '已付金额': ['paidAmount'],
  '未付金额': ['unpaidAmount'],
  '未结金额': ['unsettledAmount'],
  '毛利': ['profitAmount', 'grossProfit'],
  '成本': ['costAmount'],
  '折扣': ['discountRate'],
  '数量': ['qty'],
  '出库数量': ['qty'],
  '入库数量': ['inboundQty', 'qty'],
  '退货数量': ['returnQty', 'qty'],
  '报损数量': ['qty'],
  '报损金额': ['amount'],
  '报损日期': ['billDate'],
  '申请数量': ['qty'],
  '调拨数量': ['qty'],
  '在途数量': ['pendingQty'],
  '换算率': ['convertRate'],
  '基本单位数量': ['baseQty'],
  '单价': ['price'],
  '原价': ['originalPrice'],
  '现价': ['currentPrice', 'price'],
  '专属价格': ['currentPrice'],

  '状态': ['statusText', 'status'],
  '核销状态': ['status', 'apStatus', 'arStatus'],
  '生效状态': ['effectiveStatus', 'status'],
  '应付生成状态': ['apStatus'],
  '应付冲减状态': ['apStatus'],
  '应收生成': ['arStatus'],
  '开票状态': ['invoiceStatus', 'issueStatus'],
  '对账状态': ['reconcileStatusText', 'reconcileStatus'],
  '勾稽状态': ['matchStatus'],
  '认证状态': ['authStatus'],
  '付款状态': ['paymentStatus'],
  '到货状态': ['arrivalStatus'],
  '入库状态': ['inboundStatus'],
  '出库状态': ['outboundStatus'],
  '签收状态': ['signStatus'],
  '库存检查': ['stockCheck'],
  '信用检查': ['creditCheck'],
  '行类型': ['lineType'],
  '业务单位': ['bizUnit'],
  '业务类型': ['bizType'],

  '批次号': ['batchNo'],
  '批次': ['batchNo'],
  '盘点单号': ['sheetNo'],
  '盘点仓库': ['warehouse'],
  '盘点日期': ['countDate'],
  '盘点类型': ['countTypeText'],
  '账面数量': ['bookQty'],
  '实盘数量': ['realQty'],
  '差异数量': ['diffQty'],
  '账面金额': ['bookAmount'],
  '实盘金额': ['realAmount'],
  '差异金额': ['diffAmount'],
  '盘前金额': ['bookAmount'],
  '实盘金额': ['realAmount'],
  '制单人': ['creatorName'],
  '审核人': ['auditorName', 'auditUser'],
  '制单时间': ['createdAt', 'createTime'],
  '审核时间': ['auditTimeFormatted', 'auditTime'],
  '生产日期': ['productionDate'],
  '到期日期': ['expiryDate'],
  '库位': ['location'],
  '入库前成本': ['beforeCost'],
  '入库后成本': ['afterCost'],
  '分摊费用': ['allocatedExpense'],
  '备注': ['remark'],

  // 签收 / 拒收（V50 拒收入库单）
  '签收数量': ['signedQty'],
  '拒收数量': ['rejectQty'],
  // 销售发货单：发货金额由出库单审核生成后不再变动，与签收金额分开两列展示
  '发货金额': ['deliverAmount'],
  '拒收原因': ['rejectReason'],
  '签收人': ['signUser'],
  '签收时间': ['signTime'],
  '拒收入库单号': ['rejectInboundNo'],
  '来源发货单': ['sourceReceiptNo'],
  '本次入库数量': ['qty'],
  // rejectAmount 优先给销售发货单（签收后由明细拒收金额汇总），amount 兜底给拒收入库单明细
  '拒收金额': ['rejectAmount', 'amount'],

  // 单托盘/堆码
  '单托盘大单位数量': ['palletQty'],
  '堆码层数': ['stackLayers'],

  // 用户/角色/系统
  '账号': ['username'],
  '用户名': ['username'],
  '权限组': ['role', 'roleName'],
  '角色': ['role', 'roleName'],
  '权限组编码': ['roleCode'],
  '权限组名称': ['roleName'],
  '角色编码': ['roleCode'],
  '角色名称': ['roleName'],
  '数据范围': ['dataScope'],
  '用户数': ['userCount'],
  '菜单权限': ['menuScope'],
  '字段权限': ['fieldScope'],
  '参数键': ['paramKey'],
  '参数名称': ['paramName'],
  '当前值': ['paramValue'],
  '参数值': ['paramValue'],
  '默认值': ['defaultValue'],
  '分组': ['paramGroup'],
  '参数分组': ['paramGroup'],
  '单据类型': ['billType'],
  '前缀': ['prefix'],
  '日期格式': ['dateFormat'],
  '流水位数': ['serialLength'],
  '重置周期': ['resetCycle'],
  '示例': ['exampleNo'],

  '任务号': ['taskNo'],
  '任务名称': ['taskName'],
  '报表名称': ['reportName'],
  '模块编码': ['moduleCode'],
  '文件名': ['fileName'],
  '成功行数': ['successRows'],
  '失败行数': ['failedRows'],
  '结果说明': ['resultText'],
  '筛选条件': ['filterText'],
  '报表类型': ['reportType'],
  '对象名称': ['objectName'],
  '对象': ['objectName'],
  '收款对象': ['objectName'],
  '往来对象': ['objectName'],
  '收款对象类型': ['objectType'],
  '往来对象类型': ['objectType'],
  '余额': ['balance'],
  '已核销金额': ['verifiedAmount'],
  '已核销/余额': ['verifiedAmount'],
  '预计结款日': ['dueDate'],
  '逾期天数': ['overdueDays'],

  '创建时间': ['createdAt'],
  '完成时间': ['finishedAt'],
  '操作时间': ['operateAt'],
  '操作人': ['operatorName'],
  '创建人': ['creatorName'],
  '创建人/时间': ['creatorInfo'],
  '审核信息': ['auditInfo'],
  '制单信息': ['creatorInfo'],
  '模块': ['moduleCode'],
  '动作': ['action'],
  '结果': ['result'],
  '详情': ['detail'],
  '业务号': ['bizNo'],

  // 客户价格
  '有效期': ['validRange'],
  '生效方式': ['effectiveMode'],
  '生效时间': ['effectiveTime'],

  // 单据类扩展
  '调拨类型': ['transferType'],
  '调拨模式': ['transferMode'],
  '费用日期': ['expenseDate', 'billDate'],
  '部门': ['department'],
  '外部凭证号': ['externalVoucherNo'],
  '费用金额': ['totalAmount', 'amount'],
  '税额': ['totalTaxAmount', 'taxAmount'],
  '不含税金额': ['totalExcludingTaxAmount', 'excludingTaxAmount'],
  '收支类型': ['directionText', 'direction'],
  '费用类型': ['expenseType'],
  // untaxedAmount 优先（采购退货单：不含税金额 = 含税商品金额 − 税额，后端现算返回）；
  // amount 兜底给采购发票等原本就存不含税金额的模块用
  '不含税金额': ['untaxedAmount', 'amount'],
  '含税金额': ['taxIncludeAmount'],
  '税额': ['taxAmount'],
  '商品金额': ['goodsAmount', 'amount'],
  '最终金额': ['finalAmount', 'totalAmount'],
  '收货日期': ['receiptDate', 'billDate'],
  '已勾稽金额': ['matchedAmount'],
  '未勾稽金额': ['unmatchedAmount'],
  '已分摊金额': ['allocatedAmount'],
  '未分摊金额': ['unallocatedAmount'],
  '分摊方式': ['allocateMethod'],
  '分摊状态': ['allocateStatus'],
  '是否生成应付': ['apGenerated'],
  '是否生成往来': ['counterpartyGenerated'],
  '是否直接收付款': ['directPayment'],
  '往来单据': ['counterpartyBill'],
  '生成收货单': ['receiptGenerated'],
  '生成发货单': ['receiptGenerated'],
  '是否生成收货单': ['receiptGenerated'],
  '是否生成发货单': ['receiptGenerated'],
  '是否更新库存': ['stockUpdated'],
  '是否生成退货单': ['returnGenerated'],
  '退货原因': ['returnReason'],
  '重量(kg)': ['weight'],
  '体积(m³)': ['volume'],
}

// 状态英文码 → 中文
const STATUS_MAP = {
  NORMAL: '正常',
  STOPPED: '停用',
  FROZEN: '冻结',
  DELETED: '已删除',
  PENDING: '待审核',
  AUDITED: '已审核',
  UNVERIFIED: '未核销',
  VERIFIED: '已核销',
  EFFECTIVE: '生效中',
  EXPIRED: '已过期',
  CLOSED: '已关闭',
  ACTIVE: '正常',
  INACTIVE: '停用',
  ON: '启用',
  OFF: '禁用',
  SCHEDULED: '定时生效',
  IMMEDIATE: '立即生效',
}

// 布尔值 → 中文
function toDisplayValue(val, title) {
  if (val === null || val === undefined) return ''
  // 状态字段翻译
  if (/状态/.test(title) && typeof val === 'string' && STATUS_MAP[val]) {
    return STATUS_MAP[val]
  }
  // 布尔 → 是/否
  if (typeof val === 'boolean') return val ? '是' : '否'
  return val
}

function valueForTitle(title, record) {
  if (!title || !record) return ''
  // 精确匹配
  const keys = EXACT_TITLE_MAP[title]
  if (keys) {
    for (const key of keys) {
      if (record[key] !== undefined && record[key] !== null && record[key] !== '') {
        return toDisplayValue(record[key], title)
      }
    }
  }
  // 兜底：单一"编码"匹配任意 XxxCode 字段
  if (title === '编码' || title === '编号') {
    const codeField = Object.keys(record).find(k => /Code$/.test(k) && typeof record[k] === 'string')
    if (codeField) return toDisplayValue(record[codeField], title)
    if (record.code) return toDisplayValue(record.code, title)
  }
  // 兜底：单一"名称"匹配任意 XxxName 字段（排除 parentName/managerName 等修饰字段）
  if (title === '名称') {
    const nameField = Object.keys(record).find(k => /Name$/.test(k) && !/^(parent|manager|contact|display|role|param|task|report|module|object|file)Name$/i.test(k) && typeof record[k] === 'string')
    if (nameField) return toDisplayValue(record[nameField], title)
    if (record.name) return toDisplayValue(record.name, title)
  }
  // 兜底："类型/分组"匹配 supplierType/counterpartyType/ownerType/accountType 等
  if (title === '类型/分组' || title === '类型') {
    const typeField = Object.keys(record).find(k => /Type$/.test(k) && typeof record[k] === 'string')
    if (typeField) return toDisplayValue(record[typeField], title)
    if (record.type) return toDisplayValue(record.type, title)
  }
  // 操作列：根据状态返回不同按钮
  if (/操作/.test(title)) {
    // 调拨三模块：不显示核销
    const isTransfer = record.applyNo != null || record.outboundNo != null || record.inboundNo != null
    const st = record.statusText || record.status
    if (st === '待审核' || st === 'PENDING') {
      if (isTransfer) return '编辑 审核'
      return '编辑 审核 删除'
    }
    if (st === '已审核' || st === 'APPROVED') {
      if (isTransfer) return '反审核'
      return '核销 取消审核'
    }
    return '查看'
  }
  return ''
}
