export const moduleApis = {
  goods: { page: '/base/goods/page', save: '/base/master/save', stop: '/base/master/stop' },
  category: { page: '/base/category/page', save: '/base/category/create', stop: '/base/master/stop' },
  brand: { page: '/base/brand/page', save: '/base/master/save', stop: '/base/master/stop' },
  unit: { page: '/base/unit/page', save: '/base/master/save', stop: '/base/master/stop' },
  warehouse: { page: '/base/warehouse/page', save: '/base/master/save', stop: '/base/master/stop' },
  customer: { page: '/base/master/customer/page', save: '/base/master/save', stop: '/base/master/stop' },
  supplier: { page: '/base/master/supplier/page', save: '/base/master/save', stop: '/base/master/stop' },
  priceGroup: { page: '/base/master/price-group/page', save: '/base/master/save', stop: '/base/master/stop' },
  counterparty: { page: '/base/master/counterparty/page', save: '/base/master/save', stop: '/base/master/stop' },
  fundAccount: { page: '/base/master/fund-account/page', save: '/base/master/save', stop: '/base/master/stop' },
  expenseType: { page: '/base/master/expense-type/page', save: '/base/master/save', stop: '/base/master/stop' },
  territory: { page: '/base/master/territory/page', save: '/base/master/save', stop: '/base/master/stop' },
  routeLine: { page: '/base/master/route-line/page', save: '/base/master/save', stop: '/base/master/stop' },
  employee: { page: '/base/master/employee/page', save: '/base/master/save', stop: '/base/master/stop' },
  department: { page: '/base/master/department/page', save: '/base/master/save', stop: '/base/master/stop' },
  owner: { page: '/base/master/owner/page', save: '/base/master/save', stop: '/base/master/stop' },

  customerPrice: { page: '/base/customer-price-adjust/page', save: '/base/customer-price-adjust/create', audit: '/base/customer-price-adjust/audit', cancel: '/base/customer-price-adjust/cancel', import: '/base/customer-price-adjust/import' },
  customerPriceQuery: { page: '/base/customer-price/query', stop: '/base/customer-price/stop' },

  stockBalance: { page: '/inventory/balance/page' },
  stockLedger: { page: '/inventory/ledger/page' },
  stockLock: { page: '/inventory/lock/page' },
  batchStock: { page: '/inventory/batch/page' },
  stockWarning: { page: '/inventory/warning/page' },
  transfer: { page: '/inventory/transfer/page', audit: '/inventory/transfer/audit' },
  damage: { page: '/inventory/damage/page', audit: '/inventory/damage/audit' },
  costAdjust: { page: '/inventory/cost-adjust/page', audit: '/inventory/cost-adjust/audit' },
  stockAdjust: { page: '/inventory/cost-adjust/page', audit: '/inventory/cost-adjust/audit' },
  otherInbound: { page: '/inventory/ledger/page', audit: '/purchase/inbound/audit' },
  otherOutbound: { page: '/inventory/ledger/page', audit: '/inventory/damage/audit' },
  stockTake: { page: '/inventory/balance/page', audit: '/inventory/cost-adjust/audit' },

  purchaseOrder: { page: '/purchase/order/page', save: '/purchase/order/create', audit: '/purchase/order/audit' },
  purchaseInbound: { page: '/purchase/inbound/page', audit: '/purchase/inbound/audit' },
  purchaseReceipt: { page: '/purchase/receipt/page', audit: '/purchase/receipt/audit' },
  purchaseReturn: { page: '/purchase/return/page', audit: '/purchase/return/audit' },
  purchaseExpense: { page: '/purchase/expense/page', audit: '/purchase/expense/audit' },
  purchaseInvoice: { page: '/purchase/invoice/page' },

  quickOrder: { page: '/sales/order/page', save: '/sales/quick-order/create-and-audit', audit: '/sales/quick-order/create-and-audit' },
  salesOrder: { page: '/sales/order/page', save: '/sales/order/create', audit: '/sales/order/audit' },
  salesOutbound: { page: '/sales/outbound/page', audit: '/sales/outbound/audit' },
  salesReceipt: { page: '/sales/receipt/page', audit: '/sales/receipt/audit' },
  salesReturn: { page: '/sales/return/page', audit: '/sales/return/audit' },
  salesInvoice: { page: '/sales/invoice/page' },
  flyOrder: { page: '/sales/fly-order/page', audit: '/flow/v1-core/self-test' },
  emptyAdjust: { page: '/sales/empty-adjust/page', audit: '/flow/v1-core/self-test' },

  ar: { page: '/finance/ar/page', reconcile: '/finance/reconcile/receive' },
  ap: { page: '/finance/ap/page', reconcile: '/finance/reconcile/pay' },
  receiptPayment: { page: '/finance/receipt-payment/page', save: '/finance/receipt/create', audit: '/flow/v1-core/self-test' },
  arSettlement: { page: '/finance/ar-settlement/page', reconcile: '/finance/reconcile/receive' },
  apSettlement: { page: '/finance/ap-settlement/page', reconcile: '/finance/reconcile/pay' },
  financeExpense: { page: '/finance/expense/page', audit: '/finance/expense/audit' },
  fundLedger: { page: '/finance/fund-ledger/page' },
  counterpartyAr: { page: '/finance/ar/page', reconcile: '/finance/reconcile/receive' },
  counterpartyAp: { page: '/finance/ap/page', reconcile: '/finance/reconcile/pay' },
  receiptVerify: { page: '/finance/ar/page', reconcile: '/finance/reconcile/receive' },
  paymentVerify: { page: '/finance/ap/page', reconcile: '/finance/reconcile/pay' },
  customerStatement: { page: '/finance/ar/page' },
  supplierStatement: { page: '/finance/ap/page' },

  user: { page: '/system/user/page', save: '/system/user/save', stop: '/base/master/stop' },
  role: { page: '/system/role/page', save: '/system/role/save', stop: '/base/master/stop' },
  param: { page: '/system/param/page', save: '/system/param/update' },
  billNo: { page: '/system/bill-no-rule/page', save: '/system/bill-no-rule/update' },
  precision: { page: '/system/precision/page', save: '/system/precision/save' },
  dictionary: { page: '/system/dictionary/page', save: '/system/dictionary/save' },
  workflow: { page: '/system/workflow/page', save: '/system/workflow/save' },
  printTemplate: { page: '/system/print-template/page', save: '/system/print-template/save' },
  importList: { page: '/system/import-list/page' },
  exportCenter: { page: '/system/export-center/page', download: '/system/export-center/download' },
  log: { page: '/system/operation-log/page' },

  salesReport: { page: '/report/sales/page', export: '/report/export' },
  purchaseReport: { page: '/report/purchase/page', export: '/report/export' },
  stockReport: { page: '/report/stock/page', export: '/report/export' },
  financeReport: { page: '/report/finance/page', export: '/report/export' },
}

export function mapRecordToRow(record, config) {
  return Object.fromEntries(config.columns.map((title, index) => [`c${index}`, valueForTitle(title, record, config.row[index])]))
}

function valueForTitle(title, record, fallback = '') {
  const aliases = [
    [/(商品图片)/, ['image']],
    [/(商品编码|商品编号)/, ['goodsCode', 'code']],
    [/(商品名称|名称)/, ['goodsName', 'name']],
    [/(规格)/, ['spec']],
    [/(分类)/, ['category', 'type']],
    [/(品牌)/, ['brandName', 'brand']],
    [/(基本单位|单位)/, ['baseUnit', 'unitName', 'unit']],
    [/(条码)/, ['barcode']],
    [/(标准售价)/, ['standardPrice']],
    [/(参考进价|最新进价)/, ['latestPurchasePrice', 'referencePurchasePrice']],
    [/(最低售价)/, ['minSalePrice']],
    [/(当前库存|实物库存)/, ['physicalQty', 'currentStock']],
    [/(可用库存)/, ['availableQty']],
    [/(锁定库存)/, ['lockedQty']],
    [/(冻结库存)/, ['frozenQty']],
    [/(库存金额)/, ['stockAmount']],
    [/(成本单价|成本价)/, ['costPrice']],
    [/(客户编号\/名称|客户|门店)/, ['customer', 'customerName', 'objectName']],
    [/(供应商)/, ['supplier', 'supplierName', 'objectName']],
    [/(仓库|收货仓库|入库仓库|出库仓库)/, ['warehouse']],
    [/(采购单号|订单号|单号|入库单号|收货单号|出库单号|流水号|应收单号|应付单号)/, ['orderNo', 'billNo', 'inboundNo', 'receiptNo', 'outboundNo', 'ledgerNo', 'arNo', 'apNo', 'adjustNo', 'returnNo', 'invoiceNo', 'expenseNo', 'settlementNo']],
    [/(单据日期|日期|入库日期|出库日期|签收日期|发生时间)/, ['billDate', 'occurredAt']],
    [/(采购员)/, ['buyer']],
    [/(业务员)/, ['salesman']],
    [/(金额|订单金额|入库金额|销售金额|签收金额|应收金额|应付金额|费用金额|采购金额)/, ['amount', 'salesAmount', 'purchaseAmount', 'arAmount', 'apAmount', 'expenseAmount', 'signedAmount']],
    [/(入库金额)/, ['inboundAmount']],
    [/(毛利)/, ['grossProfit']],
    [/(报表类型)/, ['reportType']],
    [/(对象名称)/, ['objectName']],
    [/(余额)/, ['balance']],
    [/(已核销金额)/, ['verifiedAmount']],
    [/(预计日期)/, ['dueDate']],
    [/(最近出入库时间)/, ['lastInoutTime']],
    [/(已收金额|已收)/, ['receivedAmount', 'paidAmount']],
    [/(未收金额|未结金额|未付金额)/, ['unreceivedAmount', 'unpaidAmount', 'unsettledAmount']],
    [/(原价)/, ['originalPrice']],
    [/(现价|专属价格)/, ['currentPrice', 'price']],
    [/(账号|用户名)/, ['username']],
    [/(姓名|用户名称)/, ['displayName']],
    [/(手机|手机号)/, ['mobile']],
    [/(权限组|角色)/, ['role', 'roleName']],
    [/(数据范围)/, ['dataScope']],
    [/(权限组编码|角色编码)/, ['roleCode']],
    [/(权限组名称|角色名称)/, ['roleName']],
    [/(用户数)/, ['userCount']],
    [/(菜单权限)/, ['menuScope']],
    [/(字段权限)/, ['fieldScope']],
    [/(参数键)/, ['paramKey']],
    [/(参数名称)/, ['paramName']],
    [/(当前值|参数值)/, ['paramValue']],
    [/(默认值)/, ['defaultValue']],
    [/(分组|参数分组)/, ['paramGroup']],
    [/(单据类型)/, ['billType']],
    [/(前缀)/, ['prefix']],
    [/(日期格式)/, ['dateFormat']],
    [/(流水位数)/, ['serialLength']],
    [/(重置周期)/, ['resetCycle']],
    [/(示例)/, ['exampleNo']],
    [/(任务号)/, ['taskNo', 'code']],
    [/(报表名称)/, ['reportName', 'name']],
    [/(模块编码)/, ['moduleCode', 'type']],
    [/(文件名)/, ['fileName']],
    [/(筛选条件)/, ['filterText', 'remark']],
    [/(创建时间)/, ['createdAt']],
    [/(完成时间)/, ['finishedAt']],
    [/(操作时间)/, ['operateAt']],
    [/(操作人)/, ['operatorName']],
    [/(模块)/, ['moduleCode']],
    [/(动作)/, ['action']],
    [/(结果)/, ['result']],
    [/(状态|核销状态|生效状态|应付生成状态|应收生成|开票状态|勾稽状态)/, ['status', 'effectiveStatus', 'apStatus', 'arStatus', 'issueStatus', 'matchStatus']],
  ]
  for (const [pattern, keys] of aliases) {
    if (pattern.test(title)) {
      for (const key of keys) {
        if (record[key] !== undefined && record[key] !== null) return record[key]
      }
    }
  }
  if (/操作/.test(title)) return fallback || '查看 编辑'
  return fallback ?? ''
}
